version: '3'
services:
  ubahn-data-processor-es:
    image: ubahn-data-processor-es:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - api.env
    network_mode: "host"
